// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Jj_1FTnW0P3e7KMKbt5XjYOJDWYTvmU',
    appId: '1:428540903054:web:c9deb3b356dbbf793d93df',
    messagingSenderId: '428540903054',
    projectId: 'cloud-board-stationd',
    authDomain: 'cloud-board-stationd.firebaseapp.com',
    storageBucket: 'cloud-board-stationd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5vGu1AnNvpiaKuTpbT9Q-rOMooNiBEFE',
    appId: '1:428540903054:android:372a37e13694a69b3d93df',
    messagingSenderId: '428540903054',
    projectId: 'cloud-board-stationd',
    storageBucket: 'cloud-board-stationd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjjr5iUtIyuhE_DPUHFM6_nQP6Qq0Q2Ho',
    appId: '1:428540903054:ios:2483df8a16e997ba3d93df',
    messagingSenderId: '428540903054',
    projectId: 'cloud-board-stationd',
    storageBucket: 'cloud-board-stationd.firebasestorage.app',
    androidClientId: '428540903054-lvnk9aog697de6gd54rf8uqb1m7s8b2e.apps.googleusercontent.com',
    iosClientId: '428540903054-ass1pn2au4t7d7ih18u218d82pvkq3jg.apps.googleusercontent.com',
    iosBundleId: 'com.sunmkim.cloudboard',
  );
}
